server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service-db
    driver-class-name: org.h2.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka