server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka